version: "3.8"
name: loyalty-program

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development
    environment:
      RUBY_ENV: development
      TZ: "/usr/share/zoneinfo/Universal" # UTC
      REDIS_URL: redis://redis:6379/1
      DOCKER_LOGS: true
    depends_on:
      - redis
    volumes:
      - .:/app
      - app_local_bundle:/usr/local/bundle
    networks:
      - loyalty-program-net
  redis:
    image: redis:7.2.4-alpine3.19
    environment:
      TZ: "/usr/share/zoneinfo/Universal" # UTC
    networks:
      - loyalty-program-net
    ports:
      - 6379:6379

volumes:
  app_local_bundle:
networks:
  loyalty-program-net:
