#!/usr/bin/env ruby

require 'thor'

require_relative './lib/logger'
require_relative './lib/queue'
require_relative './lib/consumers'

class LoyaltyProgramCLI < Thor
  desc 'hello', 'say hello'
  def hello
    puts 'Hello'
  end

  desc 'server', 'messages and orders watcher'
  def server
    LoyaltyProgram::Logger.log 'Starting server...'
    LoyaltyProgram::Consumers.watch
  end
end

LoyaltyProgramCLI.start
